<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>@include('partials.head')</head>
<body class="min-h-screen bg-[#f5f7fa]">
<div class="min-h-screen">
    <header class="border-b border-emerald-900/10 bg-white"><div class="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><div class="flex items-center gap-3"><img src="https://ug.nsuk.edu.ng/api/global/logo" alt="NSUK crest" class="nsuk-crest size-12"><div><p class="font-semibold uppercase leading-5 text-[#016b4b]">Nasarawa State University, Keffi</p><p class="text-xs text-zinc-500">Institutional Partnership Management</p></div></div>@auth<flux:button variant="primary" :href="route('dashboard')">Open Dashboard</flux:button>@else<flux:button variant="primary" :href="route('login')">Staff Sign In</flux:button>@endauth</div></header>

    <main>
        <section class="relative overflow-hidden bg-[#016b4b] text-white"><div class="absolute inset-0 opacity-10" style="background-image:url('https://ug.nsuk.edu.ng/img/login-bg.163a8f84.jpg');background-size:cover;background-position:center"></div><div class="relative mx-auto grid max-w-7xl gap-12 px-6 py-20 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:py-28"><div><p class="text-sm font-semibold uppercase tracking-[.22em] text-emerald-200">Knowledge for development</p><h1 class="mt-5 max-w-4xl text-4xl font-semibold leading-tight text-white sm:text-5xl lg:text-6xl">Institutional MoU & Partnership Management System</h1><p class="mt-6 max-w-2xl text-base leading-8 text-white/75">A central platform for NSUK to manage partner institutions, agreements, approvals, obligations, controlled documents, renewals, and management reporting.</p><div class="mt-9 flex flex-wrap gap-3">@auth<flux:button class="!bg-white !text-[#016b4b]" :href="route('dashboard')">Go to Dashboard</flux:button>@else<flux:button class="!bg-[#16c492] !text-white" :href="route('login')">Access Staff Workspace</flux:button>@endauth</div></div><div class="nsuk-glass rounded-3xl p-8"><img src="https://ug.nsuk.edu.ng/api/global/logo" alt="NSUK crest" class="nsuk-crest mx-auto size-32"><p class="mt-7 text-center text-xl font-semibold uppercase leading-8 text-white">Nasarawa State<br>University, Keffi</p><p class="mt-4 text-center text-sm leading-6 text-white/70">Secure institutional oversight from partnership initiation through delivery and renewal.</p></div></div></section>

        <section class="mx-auto max-w-7xl px-6 py-16"><div class="grid gap-5 md:grid-cols-3"><article class="rounded-2xl border border-zinc-200 bg-white p-6"><div class="flex size-11 items-center justify-center rounded-xl bg-emerald-50 text-[#016b4b]"><flux:icon name="building-office" class="size-5"/></div><h2 class="mt-5 text-lg font-semibold">Central Partnership Registry</h2><p class="mt-2 text-sm leading-6 text-zinc-500">One trusted institutional record for partners, MoUs, contacts, ownership, and lifecycle status.</p></article><article class="rounded-2xl border border-zinc-200 bg-white p-6"><div class="flex size-11 items-center justify-center rounded-xl bg-emerald-50 text-[#016b4b]"><flux:icon name="check-circle" class="size-5"/></div><h2 class="mt-5 text-lg font-semibold">Controlled Governance</h2><p class="mt-2 text-sm leading-6 text-zinc-500">Structured reviews, approvals, signed documents, role-based access, and permanent audit history.</p></article><article class="rounded-2xl border border-zinc-200 bg-white p-6"><div class="flex size-11 items-center justify-center rounded-xl bg-emerald-50 text-[#016b4b]"><flux:icon name="chart-bar" class="size-5"/></div><h2 class="mt-5 text-lg font-semibold">Delivery Intelligence</h2><p class="mt-2 text-sm leading-6 text-zinc-500">Monitor obligations, deadlines, renewals, exceptions, alerts, and institutional performance.</p></article></div></section>
    </main>
    <footer class="border-t border-zinc-200 bg-white"><div class="mx-auto flex max-w-7xl flex-col gap-2 px-6 py-6 text-xs text-zinc-500 sm:flex-row sm:items-center sm:justify-between"><span>© {{ now()->year }} Nasarawa State University, Keffi</span><span>Institutional MoU & Partnership Tracking System</span></div></footer>
</div>
@fluxScripts
</body>
</html>
