<x-layouts::app :title="__('Audit Trail')">
<div class="mx-auto flex w-full max-w-6xl flex-1 flex-col gap-6">
    <header><p class="text-sm font-medium text-zinc-500">Governance & Accountability</p><h1 class="mt-1 text-3xl font-semibold tracking-tight">Institutional Audit Trail</h1><p class="mt-1 text-sm text-zinc-500">Permanent chronological evidence of changes across agreements, users, documents, obligations, and renewals.</p></header>
    <form method="GET" class="grid gap-3 rounded-xl border border-zinc-200 bg-white p-4 dark:border-zinc-700 dark:bg-zinc-900 sm:grid-cols-[1fr_180px_auto]"><input name="search" value="{{ request('search') }}" placeholder="Search event, agreement, or actor..." class="rounded-lg border border-zinc-200 bg-white px-3 py-2.5 text-sm dark:border-zinc-700 dark:bg-zinc-800"><select name="event" class="rounded-lg border border-zinc-200 bg-white px-3 py-2.5 text-sm dark:border-zinc-700 dark:bg-zinc-800"><option value="">All events</option>@foreach(['created','updated','deleted'] as $event)<option value="{{ $event }}" @selected(request('event')===$event)>{{ ucfirst($event) }}</option>@endforeach</select><flux:button type="submit">Filter</flux:button></form>
    <section class="overflow-hidden rounded-xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-700 dark:bg-zinc-900">
        <div class="grid grid-cols-[140px_110px_1fr] border-b border-zinc-100 bg-zinc-50 px-5 py-3 text-xs font-medium uppercase tracking-wide text-zinc-500 dark:border-zinc-800 dark:bg-zinc-800/60"><span>Date</span><span>Event</span><span>Record</span></div>
        <div class="divide-y divide-zinc-100 dark:divide-zinc-800">@forelse($events as $event)<div class="grid gap-3 px-5 py-4 sm:grid-cols-[140px_110px_1fr]"><div><p class="text-sm font-medium">{{ $event->created_at->format('d M Y') }}</p><p class="text-xs text-zinc-400">{{ $event->created_at->format('H:i') }}</p></div><div><span class="inline-flex rounded-full bg-zinc-100 px-2.5 py-1 text-xs font-medium capitalize dark:bg-zinc-800">{{ $event->event }}</span></div><div class="min-w-0">@if($event->agreement)<a href="{{ route('agreements.show', $event->agreement) }}" class="text-sm font-semibold hover:underline">{{ $event->description }}</a>@else<p class="text-sm font-semibold">{{ $event->description }}</p>@endif<p class="mt-1 text-xs text-zinc-500">{{ $event->agreement?->reference_number ?? class_basename($event->subject_type) }}</p><p class="mt-1 text-xs text-zinc-400">Recorded by {{ $event->actor?->name ?? 'System process' }}@if($event->ip_address) · {{ $event->ip_address }}@endif</p></div></div>@empty<div class="px-5 py-16 text-center"><p class="font-medium">No auditable activity yet</p><p class="mt-1 text-sm text-zinc-500">New changes will be recorded automatically.</p></div>@endforelse</div>
        @if($events->hasPages())<div class="border-t border-zinc-100 p-4 dark:border-zinc-800">{{ $events->links() }}</div>@endif
    </section>
</div>
</x-layouts::app>
