<div class="grid gap-5 sm:grid-cols-2">
<div class="sm:col-span-2"><label class="mb-1.5 block text-sm font-medium">Title *</label><input name="title" value="{{ old('title',$obligation->title ?? '') }}" required class="w-full rounded-lg border border-zinc-200 bg-white px-3 py-2.5 dark:border-zinc-700 dark:bg-zinc-800"></div>
<div><label class="mb-1.5 block text-sm font-medium">Type *</label><select name="type" class="w-full rounded-lg border border-zinc-200 bg-white px-3 py-2.5 dark:border-zinc-700 dark:bg-zinc-800">@foreach(['obligation'=>'Obligation','milestone'=>'Milestone','deliverable'=>'Deliverable'] as $v=>$l)<option value="{{ $v }}" @selected(old('type',$obligation->type ?? 'obligation')===$v)>{{ $l }}</option>@endforeach</select></div>
<div><label class="mb-1.5 block text-sm font-medium">Priority *</label><select name="priority" class="w-full rounded-lg border border-zinc-200 bg-white px-3 py-2.5 dark:border-zinc-700 dark:bg-zinc-800">@foreach(['low','medium','high','critical'] as $v)<option value="{{ $v }}" @selected(old('priority',$obligation->priority ?? 'medium')===$v)>{{ ucfirst($v) }}</option>@endforeach</select></div>
<div><label class="mb-1.5 block text-sm font-medium">Responsible Department</label><select name="department_id" class="w-full rounded-lg border border-zinc-200 bg-white px-3 py-2.5 dark:border-zinc-700 dark:bg-zinc-800"><option value="">Not assigned</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected(old('department_id',$obligation->department_id ?? $agreement->department_id)==$department->id)>{{ $department->name }}</option>@endforeach</select></div>
<div><label class="mb-1.5 block text-sm font-medium">Responsible Officer</label><select name="responsible_officer_id" class="w-full rounded-lg border border-zinc-200 bg-white px-3 py-2.5 dark:border-zinc-700 dark:bg-zinc-800"><option value="">Not assigned</option>@foreach($officers as $officer)<option value="{{ $officer->id }}" @selected(old('responsible_officer_id',$obligation->responsible_officer_id ?? $agreement->responsible_officer_id)==$officer->id)>{{ $officer->name }}</option>@endforeach</select></div>
<div><label class="mb-1.5 block text-sm font-medium">Due Date</label><input type="date" name="due_date" value="{{ old('due_date',isset($obligation) ? $obligation->due_date?->format('Y-m-d') : '') }}" class="w-full rounded-lg border border-zinc-200 bg-white px-3 py-2.5 dark:border-zinc-700 dark:bg-zinc-800"></div>
<div><label class="mb-1.5 block text-sm font-medium">Status</label><select name="status" class="w-full rounded-lg border border-zinc-200 bg-white px-3 py-2.5 dark:border-zinc-700 dark:bg-zinc-800">@foreach(['not_started'=>'Not Started','in_progress'=>'In Progress','blocked'=>'Blocked','completed'=>'Completed','cancelled'=>'Cancelled'] as $v=>$l)<option value="{{ $v }}" @selected(old('status',$obligation->status ?? 'not_started')===$v)>{{ $l }}</option>@endforeach</select></div>
<div><label class="mb-1.5 block text-sm font-medium">Progress (%)</label><input type="number" min="0" max="100" name="progress" value="{{ old('progress',$obligation->progress ?? 0) }}" class="w-full rounded-lg border border-zinc-200 bg-white px-3 py-2.5 dark:border-zinc-700 dark:bg-zinc-800"></div>
<div class="sm:col-span-2"><label class="mb-1.5 block text-sm font-medium">Description</label><textarea name="description" rows="4" class="w-full rounded-lg border border-zinc-200 bg-white px-3 py-2.5 dark:border-zinc-700 dark:bg-zinc-800">{{ old('description',$obligation->description ?? '') }}</textarea></div>
<div class="sm:col-span-2"><label class="mb-1.5 block text-sm font-medium">Completion / Progress Notes</label><textarea name="completion_notes" rows="3" class="w-full rounded-lg border border-zinc-200 bg-white px-3 py-2.5 dark:border-zinc-700 dark:bg-zinc-800">{{ old('completion_notes',$obligation->completion_notes ?? '') }}</textarea></div>
</div>