<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class AgreementAttentionNotification extends Notification
{
    use Queueable;

    public function __construct(
        public readonly int $expiringCount,
        public readonly int $overdueCount,
        public readonly string $dispatchDate,
    ) {}

    public function via(object $notifiable): array
    {
        return ['mail', 'database'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        return (new MailMessage)
            ->subject('MoU records require attention')
            ->greeting('Hello '.$notifiable->name.',')
            ->line($this->summary())
            ->action('Review Operational Alerts', route('alerts.index'))
            ->line('This automated reminder was generated by the Institutional MoU & Partnership Tracking System.');
    }

    public function toArray(object $notifiable): array
    {
        return [
            'dispatch_date' => $this->dispatchDate,
            'expiring_count' => $this->expiringCount,
            'overdue_count' => $this->overdueCount,
            'message' => $this->summary(),
            'url' => route('alerts.index'),
        ];
    }

    private function summary(): string
    {
        return "{$this->expiringCount} agreement(s) expire within 30 days and {$this->overdueCount} obligation(s) are overdue in your accessible portfolio.";
    }
}
