@csrf
@if($errors->any())<div class="mb-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/30 dark:text-red-300"><div class="flex gap-3"><flux:icon name="exclamation-triangle" class="mt-0.5 size-5 shrink-0"/><div><p class="font-semibold">We couldn't save this agreement yet.</p><p class="mt-1 text-xs opacity-80">Review the information below and correct the highlighted fields.</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div></div></div>@endif
<div class="grid gap-6 lg:grid-cols-2">
<div class="lg:col-span-2"><h2 class="font-semibold text-zinc-950 dark:text-white">Agreement Information</h2><p class="mt-1 text-sm text-zinc-500">Identify the agreement and participating institution. Fields marked required must be completed.</p></div>
<flux:input name="reference_number" label="Reference number" value="{{ old('reference_number',$agreement->reference_number ?? '') }}" placeholder="MOU-2026-001" required/><flux:input name="title" label="Agreement title" value="{{ old('title',$agreement->title ?? '') }}" placeholder="e.g. Academic and Research Collaboration" required/>
<flux:select name="partner_id" label="Partner institution" required><option value="">Select partner</option>@foreach($partners as $p)<option value="{{ $p->id }}" @selected((string)old('partner_id',$agreement->partner_id ?? $selectedPartner ?? '')===(string)$p->id)>{{ $p->name }}</option>@endforeach</flux:select>
<flux:select name="agreement_type" label="Agreement type" required>@foreach(['MoU','Partnership Agreement','Collaboration Agreement','Academic Exchange Agreement','Service Agreement','Other'] as $type)<option value="{{ $type }}" @selected(old('agreement_type',$agreement->agreement_type ?? 'MoU')===$type)>{{ $type }}</option>@endforeach</flux:select>
<div class="lg:col-span-2"><flux:textarea name="purpose" label="Purpose / Scope" rows="4" placeholder="Summarize the objectives, scope and intended outcomes of this agreement.">{{ old('purpose',$agreement->purpose ?? '') }}</flux:textarea></div>
<div class="lg:col-span-2 border-t border-zinc-100 pt-6 dark:border-zinc-800"><h2 class="font-semibold text-zinc-950 dark:text-white">Ownership & Agreement Period</h2><p class="mt-1 text-sm text-zinc-500">Assign institutional responsibility and record the proposed agreement period. Workflow status is managed automatically after creation.</p></div>
<flux:select name="department_id" label="Owning department"><option value="">Select department</option>@foreach($departments as $d)<option value="{{ $d->id }}" @selected((string)old('department_id',$agreement->department_id ?? '')===(string)$d->id)>{{ $d->name }}</option>@endforeach</flux:select>
<flux:select name="responsible_officer_id" label="Responsible officer"><option value="">Select officer</option>@foreach($officers as $o)<option value="{{ $o->id }}" @selected((string)old('responsible_officer_id',$agreement->responsible_officer_id ?? '')===(string)$o->id)>{{ $o->name }}</option>@endforeach</flux:select>
<flux:input name="start_date" type="date" label="Start date" value="{{ old('start_date',isset($agreement) ? $agreement->start_date?->format('Y-m-d') : '') }}"/><flux:input name="expiry_date" type="date" label="Expiry / review date" value="{{ old('expiry_date',isset($agreement) ? $agreement->expiry_date?->format('Y-m-d') : '') }}"/>
<div class="lg:col-span-2"><flux:textarea name="notes" label="Internal notes" rows="3" placeholder="Optional internal context for authorized officers.">{{ old('notes',$agreement->notes ?? '') }}</flux:textarea><p class="mt-1.5 text-xs text-zinc-400">Internal notes are intended for institutional users and are not part of the signed agreement.</p></div>
</div>
<div class="mt-8 flex flex-col-reverse gap-3 border-t border-zinc-100 pt-5 sm:flex-row sm:items-center sm:justify-between dark:border-zinc-800"><p class="text-xs text-zinc-400">Changes are recorded when you save this agreement.</p><div class="flex justify-end gap-3"><flux:button :href="route('agreements.index')" variant="ghost">Cancel</flux:button><flux:button type="submit" variant="primary" icon="check">{{ $submitLabel }}</flux:button></div></div>
