<x-layouts::app :title="$partner->name">
<div class="flex w-full flex-1 flex-col gap-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><a href="{{ route('partners.index') }}" class="text-sm text-zinc-500 hover:text-zinc-900 dark:hover:text-white">← Partner Registry</a><div class="mt-3 flex items-center gap-3"><div class="flex size-12 items-center justify-center rounded-xl bg-zinc-950 text-lg font-semibold text-white dark:bg-white dark:text-zinc-950">{{ strtoupper(substr($partner->name, 0, 1)) }}</div><div><h1 class="text-3xl font-semibold tracking-tight text-zinc-950 dark:text-white">{{ $partner->name }}</h1><p class="mt-1 text-sm text-zinc-500">{{ $partner->category ?: 'Institutional Partner' }} · {{ ucfirst($partner->status) }}</p></div></div></div><flux:button icon="pencil-square" :href="route('partners.edit', $partner)" variant="primary">Edit Partner</flux:button></div>
    @if(session('success'))<div class="rounded-lg border border-zinc-200 bg-zinc-50 px-4 py-3 text-sm text-zinc-700 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-200">{{ session('success') }}</div>@endif
    <div class="grid gap-6 lg:grid-cols-3">
        <section class="rounded-xl border border-zinc-200 bg-white p-5 shadow-sm dark:border-zinc-700 dark:bg-zinc-900 lg:col-span-2"><h2 class="font-semibold text-zinc-950 dark:text-white">Organization Profile</h2><div class="mt-5 grid gap-5 sm:grid-cols-2">@foreach([['Category',$partner->category],['Website',$partner->website],['Country',$partner->country],['State / Region',$partner->state],['City',$partner->city],['Address',$partner->address]] as [$label,$value])<div><p class="text-xs font-medium uppercase tracking-wide text-zinc-400">{{ $label }}</p><p class="mt-1 text-sm text-zinc-800 dark:text-zinc-200">{{ $value ?: 'Not provided' }}</p></div>@endforeach</div>@if($partner->notes)<div class="mt-6 border-t border-zinc-100 pt-5 dark:border-zinc-800"><p class="text-xs font-medium uppercase tracking-wide text-zinc-400">Notes</p><p class="mt-2 text-sm leading-6 text-zinc-600 dark:text-zinc-300">{{ $partner->notes }}</p></div>@endif</section>
        <section class="rounded-xl border border-zinc-200 bg-white p-5 shadow-sm dark:border-zinc-700 dark:bg-zinc-900"><h2 class="font-semibold text-zinc-950 dark:text-white">Primary Contact</h2><div class="mt-5 space-y-4"><div><p class="text-xs uppercase tracking-wide text-zinc-400">Contact person</p><p class="mt-1 text-sm font-medium text-zinc-800 dark:text-zinc-200">{{ $partner->contact_name ?: 'Not provided' }}</p></div><div><p class="text-xs uppercase tracking-wide text-zinc-400">Email</p><p class="mt-1 text-sm text-zinc-600 dark:text-zinc-300">{{ $partner->contact_email ?: 'Not provided' }}</p></div><div><p class="text-xs uppercase tracking-wide text-zinc-400">Phone</p><p class="mt-1 text-sm text-zinc-600 dark:text-zinc-300">{{ $partner->contact_phone ?: 'Not provided' }}</p></div></div></section>
    </div>
    <section class="rounded-xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-700 dark:bg-zinc-900"><div class="flex items-center justify-between border-b border-zinc-100 px-5 py-4 dark:border-zinc-800"><div><h2 class="font-semibold text-zinc-950 dark:text-white">Agreements & MoUs</h2><p class="mt-1 text-sm text-zinc-500">Agreements associated with this partner will appear here.</p></div><flux:button size="sm" variant="ghost" icon="plus">New MoU</flux:button></div><div class="px-5 py-12 text-center"><flux:icon name="document-text" class="mx-auto size-8 text-zinc-300"/><p class="mt-3 text-sm font-medium text-zinc-700 dark:text-zinc-200">No linked agreements yet</p><p class="mt-1 text-xs text-zinc-500">This section will connect to the MoU module in Phase 4.</p></div></section>
</div>
</x-layouts::app>
